export const ActionTypes = {
  SET_CHARACTERS: 'SET_CHARACTERS',
  SET_FILMS: 'SET_FILMS',
  SET_CHARACTER: 'SET_CHARACTER',
  SET_FILM: 'SET_FILM',
  SET_LOADING_CHARACTERS: 'SET_LOADING_CHARACTERS',
  SET_LOADING_FILMS: 'SET_LOADING_FILMS',
};
